"""Writes deck/sprites.js from the rig: every player look (front and back, with and without its
hat) and every enemy, boss and hero sprite, as 96 x 96 PNG data URLs with the feet on the
bottom rows, the way the battle renderer expects. Run: python3 deck/tools/sprites/export.py
(needs numpy and Pillow)."""
import base64, io, os, sys
sys.path.insert(0, os.path.dirname(__file__))
import figure, cast

def url(im):
    b = io.BytesIO(); im.save(b, 'PNG', optimize=True); return 'data:image/png;base64,' + base64.b64encode(b.getvalue()).decode()

def tip(s):
    t = getattr(s, 'staff_tip', None)
    return '[%.3f,%.3f]' % (t[0] / s.w, t[1] / s.h) if t else 'null'

def look_row(lid, o):
    bare = dict(o); bare['hat'] = 'none'; bare.update(cast.BARE.get(lid, {}))
    parts = []
    for key, spec, view in (('front', o, 'front'), ('back', o, 'back'), ('frontBare', bare, 'front'), ('backBare', bare, 'back')):
        s = figure.build(spec, view); parts.append("%s:'%s'" % (key, url(s.render())))
        if key == 'front': parts.append('tip:' + tip(s))
        if key == 'back': parts.append('tipBack:' + tip(s))
    gender = {'m': 'man', 'f': 'woman'}[o.get('sex', 'm')] if o.get('race') != 'human' else ''
    return "  %s:{name:'%s', gender:'%s', %s}" % (lid, o['name'], gender, ', '.join(parts))

def main():
    rows = [look_row(lid, o) for lid, o in cast.LOOKS.items()]
    src = ("/* Generated by deck/tools/sprites/export.py from the sprite rig (rig.py, figure.py, cast.py).\n"
           "   Player looks: front (camp, character screen) and back (battle), each with and without a hat;\n"
           "   tip is where the staff's focus sits, as a fraction of the image. */\n"
           "const PLAYER_LOOKS={\n" + ",\n".join(rows) + "\n};\n")
    import beasts
    if beasts.UNITS:
        urows = []
        for uid in beasts.UNITS:
            s = beasts.build(uid); urows.append("  %s:'%s'" % (uid, url(s.render())))
        src += "/* Enemies, bosses and heroes, drawn facing right. */\nconst UNIT_SPRITES={\n" + ",\n".join(urows) + "\n};\n"
    out = os.path.join(os.path.dirname(__file__), '..', '..', 'sprites.js')
    open(out, 'w').write(src); print('wrote', os.path.normpath(out), len(src), 'bytes')

if __name__ == '__main__':
    main()
