"""Writes deck/sprites.js: every player look (front and back, with and without its hat) and every
enemy, boss and hero sprite, as 96 x 96 PNG data URLs with the feet on the bottom rows, the way
the battle renderer expects. The figures are cut from the generated sheets in deck/art/sheets
(see sheetcast.py). Run: python3 deck/tools/sprites/export.py (needs numpy, scipy and Pillow)."""
import base64, io, os, sys
sys.path.insert(0, os.path.dirname(__file__))
import sheetcast as C
from PIL import Image

def url(im):
    im = im.quantize(256, method=Image.FASTOCTREE, dither=Image.Dither.NONE)   # palette PNG: a quarter the size
    b = io.BytesIO(); im.save(b, 'PNG', optimize=True); return 'data:image/png;base64,' + base64.b64encode(b.getvalue()).decode()

def tip(t):
    return '[%.3f,%.3f]' % t if t else 'null'

def look_row(race, sex):
    L = C.look(race, sex); lid = C.LOOK_IDS[(race, sex)]
    parts = ["%s:'%s'" % (k, url(L[k])) for k in ('front', 'back', 'frontBare', 'backBare')]
    parts += ["%s:'%s'" % (k, url(L[k])) for k in ('anim', 'animBare')]
    parts += ['tips:[' + ','.join(tip(t) for t in L['tips']) + ']', 'tipsBare:[' + ','.join(tip(t) for t in L['tipsBare']) + ']']
    parts += ['tip:' + tip(L['tip']), 'tipBack:' + tip(L['tipBack'])]
    return "  %s:{name:'%s', gender:'%s', %s}" % (lid, C.SEX_NAMES.get((race, sex), C.NAMES[race]), {'m': 'man', 'f': 'woman'}[sex], ', '.join(parts))

def main():
    rows = [look_row(r, s) for r in C.RACES for s in 'mf']
    urows = ["  %s:'%s'" % (uid, url(C.unit(uid))) for uid in C.UNITS]
    src = ("/* Generated by deck/tools/sprites/export.py from the sprite sheets in deck/art/sheets.\n"
           "   Player looks: front (camp, character screen) and back (battle), each with and without a hat;\n"
           "   anim is a strip of the four poses from behind (idle, walk, cast, attack), 96 px each;\n"
           "   tip is where the staff's focus sits, as a fraction of the image. */\n"
           "const PLAYER_LOOKS={\n" + ",\n".join(rows) + "\n};\n"
           "/* Enemies, bosses and heroes. */\nconst UNIT_SPRITES={\n" + ",\n".join(urows) + "\n};\n")
    out = os.path.join(os.path.dirname(__file__), '..', '..', 'sprites.js')
    open(out, 'w').write(src); print('wrote', os.path.normpath(out), len(src), 'bytes')

if __name__ == '__main__':
    main()
