"""Writes deck/sprites.js: the hand-placed wizard (hand.py) and its six variants (chars.py),
front and back, as data URLs padded to a square with the feet on the bottom row, the way
the battle renderer expects. Run: python3 deck/tools/sprites/export.py (needs Pillow)."""
import base64, io, os, sys
from PIL import Image
sys.path.insert(0, os.path.dirname(__file__))
import hand, chars

LOOKS = [('wizard', 'Hooded wizard'), ('elf_m', 'Elf'), ('elf_f', 'Elf'), ('dwarf_m', 'Dwarf'), ('dwarf_f', 'Dwarf'), ('orc_m', 'Orc'), ('orc_f', 'Orc')]
SIZE = 64

def square(im):
    sq = Image.new('RGBA', (SIZE, SIZE), (0, 0, 0, 0))
    bb = im.getbbox(); im = im.crop(bb)
    sq.alpha_composite(im, ((SIZE - im.width) // 2, SIZE - im.height))
    return sq

def scale2x(im):
    """Scale2x (EPX): doubles a pixel-art image, rounding off diagonal steps without blurring."""
    w, h = im.size; src = im.load(); out = Image.new('RGBA', (w * 2, h * 2)); dst = out.load()
    g = lambda x, y: src[min(w - 1, max(0, x)), min(h - 1, max(0, y))]
    for y in range(h):
        for x in range(w):
            P = src[x, y]; A, B, C, D = g(x, y - 1), g(x + 1, y), g(x - 1, y), g(x, y + 1)
            e0 = A if (C == A and C != D and A != B) else P
            e1 = B if (A == B and A != C and B != D) else P
            e2 = C if (D == C and D != B and C != A) else P
            e3 = D if (B == D and B != A and D != C) else P
            dst[2 * x, 2 * y], dst[2 * x + 1, 2 * y], dst[2 * x, 2 * y + 1], dst[2 * x + 1, 2 * y + 1] = e0, e1, e2, e3
    return out

def url(im):
    b = io.BytesIO(); scale2x(square(im)).save(b, 'PNG'); return 'data:image/png;base64,' + base64.b64encode(b.getvalue()).decode()

def main():
    rows = []
    for lid, name in LOOKS:
        if lid == 'wizard':
            front = hand.render(); back = hand.back(front)
            gender = ''
        else:
            front = chars.build(lid, 'front'); back = chars.build(lid, 'back')
            gender = 'man' if lid.endswith('_m') else 'woman'
        rows.append(f"  {lid}:{{name:'{name}', gender:'{gender}', front:'{url(front)}', back:'{url(back)}'}}")
    src = ("/* Generated by deck/tools/sprites/export.py: the hand-placed wizard and its elf, dwarf and\n"
           "   orc variants, front (camp, character screen) and back (battle, seen from behind). */\n"
           f"const PLAYER_LOOKS={{\n" + ",\n".join(rows) + "\n};\n")
    out = os.path.join(os.path.dirname(__file__), '..', '..', 'sprites.js')
    open(out, 'w').write(src); print('wrote', os.path.normpath(out), len(src), 'bytes')

if __name__ == '__main__':
    main()
