'use strict';
const $=id=>document.getElementById(id), fields=['name','category','status','animation','size','row','start','count','fps','notes'];
let db, records=[],selected=null,img=null,frame=0,playing=true,last=0;
const ctx=$('preview').getContext('2d');
const message=t=>$('message').textContent=t;
const request=r=>new Promise((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
async function transaction(mode,fn){const tx=db.transaction('sprites',mode);const done=new Promise((resolve,reject)=>{tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});const result=await fn(tx.objectStore('sprites'));await done;return result;}
async function init(){try{const r=indexedDB.open('hexmancers-sprites',1);r.onupgradeneeded=()=>r.result.createObjectStore('sprites',{keyPath:'id'});db=await request(r);records=await transaction('readonly',s=>request(s.getAll()));renderList();}catch(e){message('Storage unavailable: enable browser storage to use the workshop.');}}
function renderList(){ $('list').replaceChildren();for(const record of records){const b=document.createElement('button');b.textContent=record.name+' · '+record.status;b.classList.toggle('active',selected?.id===record.id);b.onclick=()=>select(record);$('list').append(b);}}
async function loadImage(data){const i=new Image();i.src=data;await i.decode();return i;}
async function select(record){try{const decoded=await loadImage(record.data);selected=record;img=decoded;frame=0;for(const f of fields)$(f).value=record[f];$('sheet').src=record.data;$('empty').hidden=true;$('editor').hidden=false;$('dimensions').textContent=img.width+'×'+img.height+' PNG';renderList();draw();}catch(e){message('Could not decode this sprite.');}}
function settings(){const size=Math.max(1,Math.min(2048,Math.floor(Number($('size').value)||128)));const cols=Math.floor(img.width/size),rows=Math.floor(img.height/size);if(!cols||!rows)return null;const row=Math.max(1,Math.min(rows,Math.floor(Number($('row').value)||1))),start=Math.max(1,Math.min(cols,Math.floor(Number($('start').value)||1))),count=Math.max(1,Math.min(cols-start+1,Math.floor(Number($('count').value)||1))),fps=Math.max(1,Math.min(60,Number($('fps').value)||10));return {size,row,start,count,fps};}
function draw(){if(!img)return;const s=settings();if(!s){ctx.clearRect(0,0,$('preview').width,$('preview').height);$('frameLabel').textContent='Frame size exceeds sheet dimensions.';return;}frame%=s.count;const c=$('preview');if(c.width!==s.size){c.width=c.height=s.size;}ctx.imageSmoothingEnabled=false;ctx.clearRect(0,0,s.size,s.size);ctx.drawImage(img,(s.start-1+frame)*s.size,(s.row-1)*s.size,s.size,s.size,0,0,s.size,s.size);$('frameLabel').textContent=($('animation').value||'Animation')+' · frame '+(frame+1)+' / '+s.count;}
function tick(time){if(playing&&img){const s=settings();if(s&&time-last>=1000/s.fps){frame=(frame+1)%s.count;last=time;draw();}}requestAnimationFrame(tick);}
async function save(){if(!selected)return;const s=settings();if(!s){message('Choose a frame size that fits the sheet.');return;}const updated={...selected};for(const f of fields)updated[f]=$(f).value;Object.assign(updated,s);updated.name=updated.name.trim()||'Untitled sprite';await transaction('readwrite',store=>store.put(updated));records=records.map(r=>r.id===updated.id?updated:r);selected=updated;renderList();message('Review saved.');}
function download(url,name){const a=document.createElement('a');a.href=url;a.download=name;a.click();}
async function guarded(fn){try{await fn();}catch(e){message('Operation failed: '+e.message);}}
$('upload').onchange=()=>guarded(async()=>{for(const file of $('upload').files){if(file.size>25*1024*1024)throw Error('PNG exceeds 25 MB.');const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.readAsDataURL(file);});if(!data.startsWith('data:image/png;'))throw Error('Please import PNG files.');const decoded=await loadImage(data);const record={id:crypto.randomUUID(),data,name:file.name.replace(/\.png$/i,''),category:'Character',status:'Draft',animation:'Idle',size:128,row:1,start:1,count:Math.max(1,Math.min(12,Math.floor(decoded.width/128))),fps:10,notes:''};await transaction('readwrite',s=>s.put(record));records.push(record);await select(record);}message('Imported and saved.');$('upload').value='';});
for(const f of fields)$(f).addEventListener('input',draw);
$('save').onclick=()=>guarded(save);
$('play').onclick=()=>{playing=!playing;$('play').textContent=playing?'Pause':'Play';};
$('step').onclick=()=>{playing=false;$('play').textContent='Play';frame++;draw();};
$('frameDownload').onclick=()=>{if(settings())download($('preview').toDataURL('image/png'),selected.name+'-frame-'+(frame+1)+'.png');};
$('sheetDownload').onclick=()=>download(selected.data,selected.name+'.png');
$('delete').onclick=()=>guarded(async()=>{if(!selected||!confirm('Delete this sprite and its review notes from this browser?'))return;await transaction('readwrite',s=>s.delete(selected.id));records=records.filter(r=>r.id!==selected.id);selected=null;img=null;$('editor').hidden=true;$('empty').hidden=false;renderList();message('Sprite deleted.');});
$('export').onclick=()=>guarded(async()=>{await save();const url=URL.createObjectURL(new Blob([JSON.stringify({version:1,sprites:records})],{type:'application/json'}));download(url,'hexmancers-sprites-backup.json');setTimeout(()=>URL.revokeObjectURL(url),1000);});
$('restore').onclick=()=>$('backup').click();
$('backup').onchange=()=>guarded(async()=>{const file=$('backup').files[0];if(!file)return;const backup=JSON.parse(await file.text());if(backup.version!==1||!Array.isArray(backup.sprites))throw Error('Invalid backup.');const restored=[];for(const r of backup.sprites){if(typeof r.data!=='string'||!r.data.startsWith('data:image/png;')||typeof r.name!=='string'||!fields.every(f=>['string','number'].includes(typeof r[f])))throw Error('Invalid sprite entry.');await loadImage(r.data);restored.push({...r,id:crypto.randomUUID()});}await transaction('readwrite',s=>{for(const r of restored)s.put(r);});records.push(...restored);renderList();message('Restored '+restored.length+' sprites.');$('backup').value='';});
init();requestAnimationFrame(tick);
