# Build deck/sprites.js from the sprite lab's game frames (lab/game/<id>.json, written by export_game.js).
#   python3 make_sprites.py <lab dir>
# Each sprite is cropped to a square frame with the ground line at 31/32 of its height (where battle.js
# stands units) and the figure filling the frame as much as the sprite it replaces did, so sizes in the
# game stay as players know them. Enemies, heroes and bosses are mirrored to face right: the game
# draws every unit facing right and flips it toward its target. Pixels are never resampled.
import sys, os, re, json, base64, io, math
from PIL import Image
LAB=sys.argv[1]; DECK=os.path.join(os.path.dirname(os.path.abspath(__file__)),'..','..')
old=open(sys.argv[2] if len(sys.argv)>2 else os.path.join(DECK,'sprites.js')).read()
def dec(u): return Image.open(io.BytesIO(base64.b64decode(u.split(',',1)[1]))).convert('RGBA')
def enc(im):
  b=io.BytesIO(); im.save(b,'PNG',optimize=True); return 'data:image/png;base64,'+base64.b64encode(b.getvalue()).decode()
def fill(im):  # how much of the frame's height the old figure took
  bb=im.getbbox(); return (bb[3]-bb[1])/im.height if bb else .8
def load(id): return json.load(open(os.path.join(LAB,'game',id+'.json')))
def frame_info(f):
  im=dec(f['url']); cell=f['cell']; ground=cell-round(cell*.06); bb=im.getbbox(); return im,cell,ground,bb
def crop(im,cell,ground,C,mirror):
  # a CxC window: ground at 31/32 of C, centred on the figure's root (the cell's centre column)
  top=ground+C/32-C; left=cell/2-C/2; out=Image.new('RGBA',(C,C)); out.alpha_composite(im,(int(round(-left)),int(round(-top))))
  return out.transpose(Image.FLIP_LEFT_RIGHT) if mirror else out
def size_for(frames,r):
  need=0
  for im,cell,ground,bb in frames:
    if not bb: continue
    h=ground-bb[1]; half=max(cell/2-bb[0],bb[2]-cell/2)
    need=max(need,math.ceil(h/r),math.ceil(2*half/.98),math.ceil((h)/.96))
  return int(need)
def tipfrac(t,cell,ground,C,mirror):
  if not t: return None
  x=t[0]-(cell/2-C/2); y=t[1]-(ground+C/32-C); x=C-x if mirror else x
  return [round(x/C,3),round(y/C,3)]

# old player looks: keep names, genders and the figure size
looks=re.findall(r"\n  ([a-z_]+):\{name:'([^']*)', gender:'([^']*)', (.*?)\},?(?=\n)",old,re.S)
P=[]
for id,name,gender,body in looks:
  ob=re.search(r"back:'(data:[^']+)'",body).group(1); r=fill(dec(ob))
  d=load(id)['frames']; fr={k:frame_info(v) for k,v in d.items()}; C=size_for(fr.values(),r)
  g=lambda k: enc(crop(*fr[k][:3],C,False))
  def strip(pre):
    ims=[crop(*fr[pre+str(i)][:3],C,False) for i in range(4)]; s=Image.new('RGBA',(C*4,C))
    for i,im in enumerate(ims): s.alpha_composite(im,(i*C,0))
    return enc(s)
  tp=lambda k: tipfrac(d[k]['tip'],fr[k][1],fr[k][2],C,False)
  e=dict(name=name,gender=gender,front=g('front'),back=g('back'),frontBare=g('frontBare'),backBare=g('backBare'),tip=None,tipBack=tp('back'),
         anim=strip('anim'),animBare=strip('animBare'),tips=[tp('anim'+str(i)) for i in range(4)],tipsBare=[tp('animBare'+str(i)) for i in range(4)])
  P.append((id,e)); print(id,C)

# units: enemies, bosses, heroes; plus the minibosses and their helpers (new art; they used to be tinted copies)
units=re.findall(r"\n  ([a-z_]+):'(data:[^']+)'",old.split('const UNIT_SPRITES=')[1])
LABID={'witch':'witch_e'}
U=[]
for id,u in units:
  r=fill(dec(u)); d=load(LABID.get(id,id))['frames']['unit']; f=frame_info(d); C=size_for([f],r); U.append((id,enc(crop(*f[:3],C,True)))); print(id,C)
MINI={'executioner':'knight','corruptknight':'paladin','dungeonwarden':'knight','alchemist':'caller','assassin':'shade','construct':'golem','bonecollector':'witch','jailer':'knight','bonewalker':'clone','mimic':None,'giant_mimic':None}
oldU=dict(units)
for id,base in MINI.items():
  r=fill(dec(oldU[base])) if base else .62
  d=load(id)['frames']['unit']; f=frame_info(d); C=size_for([f],r); U.append((id,enc(crop(*f[:3],C,True)))); print(id,C)

# weapon icons: trimmed to the item with a pixel of air
W=[]
for fn in sorted(os.listdir(os.path.join(LAB,'game'))):
  if not fn.startswith('w_'): continue
  d=json.load(open(os.path.join(LAB,'game',fn)))['frames']['icon']; im=dec(d['url']); bb=im.getbbox(); im=im.crop((bb[0]-1,bb[1]-1,bb[2]+1,bb[3]+1))
  n=max(im.size); sq=Image.new('RGBA',(n,n)); sq.alpha_composite(im,((n-im.width)//2,(n-im.height)//2)); W.append((fn[2:-5],enc(sq)))

js=["/* Generated by deck/tools/sprite3d/make_sprites.py from the sprite lab (deck/tools/sprite3d).",
"   Player looks: front (camp, character screen) and back (battle), each with and without a hat; anim is the",
"   back view in four poses (idle, walk, cast, attack) side by side; tip is where the staff's focus sits, as a",
"   fraction of the image. Frames are square, any size; units stand with their feet at 31/32 of the height. */",
"const PLAYER_LOOKS={"]
for id,e in P:
  js.append("  %s:{name:%s, gender:%s, front:'%s', back:'%s', frontBare:'%s', backBare:'%s', tip:null, tipBack:%s, anim:'%s', animBare:'%s', tips:%s, tipsBare:%s},"%(
    id,json.dumps(e['name']).replace('"',"'"),json.dumps(e['gender']).replace('"',"'"),e['front'],e['back'],e['frontBare'],e['backBare'],json.dumps(e['tipBack']),e['anim'],e['animBare'],json.dumps(e['tips']),json.dumps(e['tipsBare'])))
js.append("};\n/* Enemies, bosses, heroes, minibosses and their helpers, facing right. */\nconst UNIT_SPRITES={")
for id,u in U: js.append("  %s:'%s',"%(id,u))
js.append("};\n/* Weapon icons. */\nconst GEAR_SPRITES={")
for id,u in W: js.append("  %s:'%s',"%(id,u))
js.append("};\n")
open(os.path.join(DECK,'sprites.js'),'w').write('\n'.join(js)); print('sprites.js',os.path.getsize(os.path.join(DECK,'sprites.js')))
